### ISSUE TITLE
[feature request] export svg file

### ISSUE THREAD

**Issue by drocsid** [ivan111/vtree#2]
I found this tool extremely useful, and was surprised I didn't find many other implementations of something similar. Unfortunatly,  I have not really spent much time hacking javascript . It's a shame because it would be nice to add a feature to export the diagram svg so we could get a nice resizable image that we could render.

**Comment by ivan111** [comment]
I added the feature.
see the bottom of [the site](https://vanya.jp.net/vtree/).

**Comment by drocsid** [comment]
Awesome! It worked well for me. Thanks for this useful tool!
